/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerticalsRouteImport } from './routes/verticals'
import { Route as UsuariosRouteImport } from './routes/usuarios'
import { Route as PipelineRouteImport } from './routes/pipeline'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ImportExportRouteImport } from './routes/import-export'
import { Route as IndexRouteImport } from './routes/index'

const VerticalsRoute = VerticalsRouteImport.update({
  id: '/verticals',
  path: '/verticals',
  getParentRoute: () => rootRouteImport,
} as any)
const UsuariosRoute = UsuariosRouteImport.update({
  id: '/usuarios',
  path: '/usuarios',
  getParentRoute: () => rootRouteImport,
} as any)
const PipelineRoute = PipelineRouteImport.update({
  id: '/pipeline',
  path: '/pipeline',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ImportExportRoute = ImportExportRouteImport.update({
  id: '/import-export',
  path: '/import-export',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/import-export': typeof ImportExportRoute
  '/login': typeof LoginRoute
  '/pipeline': typeof PipelineRoute
  '/usuarios': typeof UsuariosRoute
  '/verticals': typeof VerticalsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/import-export': typeof ImportExportRoute
  '/login': typeof LoginRoute
  '/pipeline': typeof PipelineRoute
  '/usuarios': typeof UsuariosRoute
  '/verticals': typeof VerticalsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/import-export': typeof ImportExportRoute
  '/login': typeof LoginRoute
  '/pipeline': typeof PipelineRoute
  '/usuarios': typeof UsuariosRoute
  '/verticals': typeof VerticalsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/import-export'
    | '/login'
    | '/pipeline'
    | '/usuarios'
    | '/verticals'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/import-export'
    | '/login'
    | '/pipeline'
    | '/usuarios'
    | '/verticals'
  id:
    | '__root__'
    | '/'
    | '/import-export'
    | '/login'
    | '/pipeline'
    | '/usuarios'
    | '/verticals'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ImportExportRoute: typeof ImportExportRoute
  LoginRoute: typeof LoginRoute
  PipelineRoute: typeof PipelineRoute
  UsuariosRoute: typeof UsuariosRoute
  VerticalsRoute: typeof VerticalsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verticals': {
      id: '/verticals'
      path: '/verticals'
      fullPath: '/verticals'
      preLoaderRoute: typeof VerticalsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/usuarios': {
      id: '/usuarios'
      path: '/usuarios'
      fullPath: '/usuarios'
      preLoaderRoute: typeof UsuariosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pipeline': {
      id: '/pipeline'
      path: '/pipeline'
      fullPath: '/pipeline'
      preLoaderRoute: typeof PipelineRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/import-export': {
      id: '/import-export'
      path: '/import-export'
      fullPath: '/import-export'
      preLoaderRoute: typeof ImportExportRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ImportExportRoute: ImportExportRoute,
  LoginRoute: LoginRoute,
  PipelineRoute: PipelineRoute,
  UsuariosRoute: UsuariosRoute,
  VerticalsRoute: VerticalsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
